<a href="https://colab.research.google.com/github/MasoodaAntule/NLP_project/blob/main/nlp_project_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install contractions

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 kB 13.1 MB/s eta 0:00:00


In [ ]:
 pip install unidecode

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 2.1 MB/s eta 0:00:00


In [ ]:
pip install autocorrect

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 622.8/622.8 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for autocorrect: filename=autocorrect-2.6.1-py3-none-any.whl size=622364 sha256=7e385e887ee8e7b02d91567f1e4b5c7d51a7415657bfc643e343a61395cda21c
  Stored in directory: /root/.cache/pip/wheels/b5/7b/6d/b76b29ce11ff8e2521c8c7dd0e5bfee4fb1789d76193124343
Successfully built autocorrect


nltk = natural language tookit

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from string import punctuation
import contractions
from unidecode import unidecode
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from autocorrect import Speller

In [ ]:
data = pd.read_csv('Train!.csv',error_bad_lines=False, engine="python")
data.head(10)

<ipython-input-5-1da09f1c0a43>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv('Train!.csv',error_bad_lines=False, engine="python")
Skipping line 5561: unexpected end of data


text  label
0  I grew up (b. 1965) watching and loving the Th...      0
1  When I put this movie in my DVD player, and sa...      0
2  Why do people who do not know what a particula...      0
3  Even though I have great interest in Biblical ...      0
4  Im a die hard Dads Army fan and nothing will e...      1
5  A terrible movie as everyone has said. What ma...      0
6  Finally watched this shocking movie last night...      1
7  I caught this film on AZN on cable. It sounded...      0
8  It may be the remake of 1987 Autumn's Tale aft...      1
9  My Super Ex Girlfriend turned out to be a plea...      1

In [ ]:
data.text

0       I grew up (b. 1965) watching and loving the Th...
1       When I put this movie in my DVD player, and sa...
2       Why do people who do not know what a particula...
3       Even though I have great interest in Biblical ...
4       Im a die hard Dads Army fan and nothing will e...
                              ...                        
5554    In & Out was a funny comedy with good performa...
5555    Okay, maybe this movie not a revolution. But i...
5556    The final installment sees Sho Aikawa and Riki...
5557    I love this show. I watch all the reruns every...
5558    This film stands as one of the most amazing ex...
Name: text, Length: 5559, dtype: object

In [ ]:
data.label

0       0
1       0
2       0
3       0
4       1
       ..
5554    1
5555    1
5556    1
5557    1
5558    1
Name: label, Length: 5559, dtype: int64

In [ ]:
data['text'][1]

"When I put this movie in my DVD player, and sat down with a coke and some chips, I had some expectations. I was hoping that this movie would contain some of the strong-points of the first movie: Awsome animation, good flowing story, excellent voice cast, funny comedy and a kick-ass soundtrack. But, to my disappointment, not any of this is to be found in Atlantis: Milo's Return. Had I read some reviews first, I might not have been so let down. The following paragraph will be directed to those who have seen the first movie, and who enjoyed it primarily for the points mentioned.<br /><br />When the first scene appears, your in for a shock if you just picked Atlantis: Milo's Return from the display-case at your local videoshop (or whatever), and had the expectations I had. The music feels as a bad imitation of the first movie, and the voice cast has been replaced by a not so fitting one. (With the exception of a few characters, like the voice of Sweet). The actual drawings isnt that bad, 

In [ ]:
from nltk.corpus import stopwords

In [ ]:
#1. remove spaces,newlines
def remove_spaces(data):
    clean_text = data.replace('\\n',' ').replace('\t',' ').replace('\\',' ')
    return clean_text

#2.contraction mapping
def expand_text(data):
    expanded_text = contractions.fix(data)
    return expanded_text

#3. handling accented characters
def handling_accented(data):
    fixed_text = unidecode(data)
    return fixed_text



def clean_data(data):
    tokens = word_tokenize(data)
    clean_text = [word.lower() for word in tokens if
                  (word not in punctuation) and (word.lower()
                  not in stopword_list) and (len(word)>2) and
                  (word.isalpha())]
    return clean_text

# autocorrect
def autocorrection(data):
    spell = Speller(lang='en')
    corrected_text = spell(data)
    return corrected_text

# lemmatization
def lemmatization(data):
    lemmatizer = WordNetLemmatizer()
    final_data = []
    for word in data:
        lemmatized_word = lemmatizer.lemmatize(word)
        final_data.append(lemmatized_word)
    return ' '.join(final_data)


In [ ]:
import nltk


In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#4. Cleaning
stopword_list = stopwords.words('english')
stopword_list.remove('no')
stopword_list.remove('nor')
stopword_list.remove('not')

In [ ]:
def remove_spaces(data):
    clean_text = data.replace('\\n',' ').replace('\t',' ').replace('\\',' ')
    return clean_text
remove_spaces(data['text'][1])

"When I put this movie in my DVD player, and sat down with a coke and some chips, I had some expectations. I was hoping that this movie would contain some of the strong-points of the first movie: Awsome animation, good flowing story, excellent voice cast, funny comedy and a kick-ass soundtrack. But, to my disappointment, not any of this is to be found in Atlantis: Milo's Return. Had I read some reviews first, I might not have been so let down. The following paragraph will be directed to those who have seen the first movie, and who enjoyed it primarily for the points mentioned.<br /><br />When the first scene appears, your in for a shock if you just picked Atlantis: Milo's Return from the display-case at your local videoshop (or whatever), and had the expectations I had. The music feels as a bad imitation of the first movie, and the voice cast has been replaced by a not so fitting one. (With the exception of a few characters, like the voice of Sweet). The actual drawings isnt that bad, 

Feature Scalling :text = numerical formate = vector
    this process is know as = word emeading
    1)Frequency based:- a)count vectorizer     
                        b)tfidf  
    2)Prediction Based:-a)word2vec
                        b)fast text
                        c)doc2vec

In [ ]:
#  to aviod the data leakage
x_train,x_test,y_train,y_test = train_test_split(data.text,data.label,test_size=0.25,random_state=42)

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
clean_text_train = x_train.apply(remove_spaces)
clean_text_test = x_test.apply(remove_spaces)

clean_text_train = clean_text_train.apply(expand_text)
clean_text_test = clean_text_test.apply(expand_text)

clean_text_train = clean_text_train.apply(handling_accented)
clean_text_test = clean_text_test.apply(handling_accented)

clean_text_train = clean_text_train.apply(clean_data)
clean_text_test = clean_text_test.apply(clean_data)

clean_text_train = clean_text_train.apply(lemmatization)
clean_text_test = clean_text_test.apply(lemmatization)

In [ ]:
clean_text_train

517     not know expect decided watch documentary knew...
3971    pretty surprised see movie earned even lukewar...
2083    early career abe lincoln beautifully presented...
3789    original vanishing point great flick subtle mo...
217     video audio meant someone hear sleep said morg...
                              ...                        
3772    lucky enough win free pass sneak preview pod l...
5191    one horrible movie seen awhile wonder john bor...
5226    remember terrible war movie grandmother forced...
5390    woman never looked attractive pathetic salazar...
860     one boot one point doctor assistant refers wor...
Name: text, Length: 4169, dtype: object

In [ ]:
# count vectorizer
count = CountVectorizer(max_df=0.95,max_features=1000)
count_val_train = count.fit_transform(clean_text_train)
count_val_test = count.transform(clean_text_test)


#count vecorizers out put is in the sparse matrix

In [ ]:
count_val_train
#print(count_val_train)

<4169x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 227159 stored elements in Compressed Sparse Row format>

In [ ]:
count_val_train.A

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
count_val_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from collections import Counter

In [ ]:
#count.get_feature_names()
count.get_feature_names_out()

array(['ability', 'able', 'absolutely', 'accent', 'across', 'act',
       'acted', 'acting', 'action', 'actor', 'actress', 'actual',
       'actually', 'add', 'added', 'admit', 'adult', 'adventure', 'age',
       'ago', 'agree', 'air', 'alien', 'alive', 'almost', 'alone',
       'along', 'already', 'also', 'although', 'always', 'amazing',
       'america', 'american', 'among', 'amount', 'animal', 'animation',
       'annoying', 'another', 'answer', 'anyone', 'anything', 'anyway',
       'apart', 'apparently', 'appeal', 'appear', 'appearance', 'appears',
       'around', 'art', 'aside', 'ask', 'aspect', 'atmosphere', 'attempt',
       'attention', 'audience', 'average', 'avoid', 'award', 'away',
       'awesome', 'awful', 'baby', 'back', 'background', 'bad', 'badly',
       'band', 'barely', 'based', 'basic', 'basically', 'batman',
       'battle', 'beautiful', 'beauty', 'became', 'become', 'becomes',
       'bed', 'begin', 'beginning', 'behind', 'belief', 'believable',
       'believe'

In [ ]:
len(count.get_feature_names_out())

1000

In [ ]:
pd.DataFrame(count_val_train.A,columns=count.get_feature_names_out())

ability  able  absolutely  accent  across  act  acted  acting  action  \
0           0     0           0       0       0    0      0       0       0   
1           0     0           0       0       0    0      0       0       0   
2           0     0           0       0       0    0      0       0       0   
3           0     0           0       0       0    0      0       0       0   
4           0     0           0       0       0    0      0       0       0   
...       ...   ...         ...     ...     ...  ...    ...     ...     ...   
4164        0     0           1       0       0    0      0       0       0   
4165        0     0           0       0       0    0      0       0       0   
4166        0     0           0       0       0    0      0       0       0   
4167        0     0           0       0       0    1      0       0       0   
4168        0     0           0       0       0    0      0       1       0   

      actor  ...  wrong  wrote  yeah  year  yes  yet  york  young  younger  \
0         0  ...      0      0     0     1    0    0     0      0        0   
1         0  ...      0      0     0     0    0    0     0      0        0   
2         0  ...      0      0     0     0    0    0     0      0        0   
3         0  ...      0      0     0     0    0    0     0      0        0   
4         0  ...      0      0     0     0    0    0     0      0        0   
...     ...  ...    ...    ...   ...   ...  ...  ...   ...    ...      ...   
4164      0  ...      0      0     0     0    0    0     0      0        0   
4165      0  ...      0      0     0     0    0    0     0      0        0   
4166      0  ...      0      0     0     1    0    0     0      0        0   
4167      0  ...      0      0     0     0    0    0     0      0        0   
4168      0  ...      1      0     0     0    0    0     0      0        0   

      zombie  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
4164       0  
4165       0  
4166       0  
4167       0  
4168       0  

[4169 rows x 1000 columns]

In [ ]:
# build model
count_mnb = MultinomialNB()
count_mnb.fit(count_val_train.A,y_train)
predict_count = count_mnb.predict(count_val_test.A)
accuracy_count = accuracy_score(y_test,predict_count)*100
accuracy_count

81.58273381294964

In [ ]:
tfidf = TfidfVectorizer(max_df=0.95,max_features=1000)
tfidf_train = tfidf.fit_transform(clean_text_train)
tfidf_test = tfidf.transform(clean_text_test)

In [ ]:
tfidf_train

<4169x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 227159 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf_train.A

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tfidf_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tfidf.get_feature_names_out()

array(['ability', 'able', 'absolutely', 'accent', 'across', 'act',
       'acted', 'acting', 'action', 'actor', 'actress', 'actual',
       'actually', 'add', 'added', 'admit', 'adult', 'adventure', 'age',
       'ago', 'agree', 'air', 'alien', 'alive', 'almost', 'alone',
       'along', 'already', 'also', 'although', 'always', 'amazing',
       'america', 'american', 'among', 'amount', 'animal', 'animation',
       'annoying', 'another', 'answer', 'anyone', 'anything', 'anyway',
       'apart', 'apparently', 'appeal', 'appear', 'appearance', 'appears',
       'around', 'art', 'aside', 'ask', 'aspect', 'atmosphere', 'attempt',
       'attention', 'audience', 'average', 'avoid', 'award', 'away',
       'awesome', 'awful', 'baby', 'back', 'background', 'bad', 'badly',
       'band', 'barely', 'based', 'basic', 'basically', 'batman',
       'battle', 'beautiful', 'beauty', 'became', 'become', 'becomes',
       'bed', 'begin', 'beginning', 'behind', 'belief', 'believable',
       'believe'

In [ ]:
len(tfidf.get_feature_names_out())

1000

In [ ]:
pd.DataFrame(tfidf_train.A,columns=tfidf.get_feature_names_out())

ability  able  absolutely  accent  across       act  acted    acting  \
0         0.0   0.0    0.000000     0.0     0.0  0.000000    0.0  0.000000   
1         0.0   0.0    0.000000     0.0     0.0  0.000000    0.0  0.000000   
2         0.0   0.0    0.000000     0.0     0.0  0.000000    0.0  0.000000   
3         0.0   0.0    0.000000     0.0     0.0  0.000000    0.0  0.000000   
4         0.0   0.0    0.000000     0.0     0.0  0.000000    0.0  0.000000   
...       ...   ...         ...     ...     ...       ...    ...       ...   
4164      0.0   0.0    0.119503     0.0     0.0  0.000000    0.0  0.000000   
4165      0.0   0.0    0.000000     0.0     0.0  0.000000    0.0  0.000000   
4166      0.0   0.0    0.000000     0.0     0.0  0.000000    0.0  0.000000   
4167      0.0   0.0    0.000000     0.0     0.0  0.094638    0.0  0.000000   
4168      0.0   0.0    0.000000     0.0     0.0  0.000000    0.0  0.050628   

      action  actor  ...     wrong  wrote  yeah      year  yes  yet  york  \
0        0.0    0.0  ...  0.000000    0.0   0.0  0.082750  0.0  0.0   0.0   
1        0.0    0.0  ...  0.000000    0.0   0.0  0.000000  0.0  0.0   0.0   
2        0.0    0.0  ...  0.000000    0.0   0.0  0.000000  0.0  0.0   0.0   
3        0.0    0.0  ...  0.000000    0.0   0.0  0.000000  0.0  0.0   0.0   
4        0.0    0.0  ...  0.000000    0.0   0.0  0.000000  0.0  0.0   0.0   
...      ...    ...  ...       ...    ...   ...       ...  ...  ...   ...   
4164     0.0    0.0  ...  0.000000    0.0   0.0  0.000000  0.0  0.0   0.0   
4165     0.0    0.0  ...  0.000000    0.0   0.0  0.000000  0.0  0.0   0.0   
4166     0.0    0.0  ...  0.000000    0.0   0.0  0.090661  0.0  0.0   0.0   
4167     0.0    0.0  ...  0.000000    0.0   0.0  0.000000  0.0  0.0   0.0   
4168     0.0    0.0  ...  0.076785    0.0   0.0  0.000000  0.0  0.0   0.0   

      young  younger  zombie  
0       0.0      0.0     0.0  
1       0.0      0.0     0.0  
2       0.0      0.0     0.0  
3       0.0      0.0     0.0  
4       0.0      0.0     0.0  
...     ...      ...     ...  
4164    0.0      0.0     0.0  
4165    0.0      0.0     0.0  
4166    0.0      0.0     0.0  
4167    0.0      0.0     0.0  
4168    0.0      0.0     0.0  

[4169 rows x 1000 columns]

In [ ]:
tfidf_mnb = MultinomialNB()
tfidf_mnb.fit(tfidf_train.A,y_train)
predict_tfidf=tfidf_mnb.predict(tfidf_test.A)
accuracy_tfidf = accuracy_score(y_test,predict_tfidf)*100
accuracy_tfidf

82.0863309352518

In [ ]:
accuracy_count

81.58273381294964

In [ ]:
from nltk.util import ngrams
# [w1 w2 w3]
def splitting_dataframe(data):
    tokens = data.split()
    return tokens

data = clean_text_test.apply(splitting_dataframe)

def ngram_list(data,ngram_range):
    ngram = ngrams(data,ngram_range) # zip file
    ngram_list1 = []
    for ngram1 in ngram: #opening the zip file
        ngram_list1.append(' '.join(ngram1))
    return ngram_list1

In [ ]:
unigrams = data.apply(lambda x : ngram_list(x,1)) # x >> single review
unigrams

4963    [must, preface, saying, huge, romantic, hence,...
4943    [stalingrad, terrific, movie, well, acted, dir...
4345    [house, dead, dead, aim, sequel, though, reall...
230     [return, horror, movie, come, scream, not, sca...
1044    [unfortunately, movie, never, made, dvd, saw, ...
                              ...                        
2765    [emma, favourite, jane, austen, novel, emma, d...
1672     [ming, merciless, little, bardwork, movie, foul]
1505    [seen, movie, countes, time, still, not, get, ...
2962    [lackawanna, blue, touching, story, nanny, wom...
5264    [watched, film, hundred, time, really, best, s...
Name: text, Length: 1390, dtype: object

In [ ]:
#bigrams = data.apply(lambda x : ngram_list1(x,2)) # x >> single review
#bigrams

In [ ]:
#trigrams = data.apply(lambda x : ngram_list1(x,3)) # x >> single review
#trigrams